#!/usr/bin/env python
# vim: set fileencoding=utf-8 sw=4 ts=4 et :

"""
dedup-same

Freezes files, checks them for being identical,
and projects the extents of the first file onto the other files.

The effects are visible with filefrag -v (apt:e2fsprogs),
which displays the extent map of files.
"""

import argparse
import sys

from dedup import dedup_same


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source', metavar='SRC', help='source file')
    parser.add_argument('dests', metavar='DEST', nargs='+', help='dest files')
    parser.add_argument(
        '--defragment', action='store_true',
        help='defragment the source file first')
    opts = parser.parse_args()
    return dedup_same(opts.source, opts.dests, opts.defragment)


if __name__ == '__main__':
    sys.exit(main())

