#!/bin/bash
set -e
cd "$(dirname "$0")"
mount -t proc proc /proc
mount -t sysfs sysfs /sys
eval "$(python3 -Sc 'import urllib.parse, sys; print(urllib.parse.unquote(sys.argv[1]))' "$BEDUP_CMD")"
halt -f

